# buildspec.yml
version: 0.2

env:
  variables:
    SNOWFLAKE_ACCOUNT: "YWCMEWI-NQ94599"
    SNOWFLAKE_USER: "VINHQUOC2049"
    SNOWFLAKE_ROLE: "ACCOUNTADMIN" # WARNING: Consider using a least-privilege role for production
    SNOWFLAKE_WAREHOUSE: "COMPUTE_WH"
    SNOWFLAKE_DATABASE: "OPERATION"
    SNOWFLAKE_SCHEMA: "PUBLIC"
    SNOWFLAKE_GIT_STAGE: "OPERATION.SAC_MONITORING.SAC_GIT_REPO"

  # --- SECURELY RETRIEVE PRIVATE KEY AND PASSPHRASE FROM SECRETS MANAGER ---
  # IMPORTANT: Replace 'your-secrets-manager-secret-name-for-private-key' and 'your-json-key-name-for-private-key'
  # with the EXACT names as they appear in AWS Secrets Manager.
  # If your secret 'my_cicd_key_secret' contains both keys:
  secrets-manager:
    PRIVATE_KEY_CONTENT_VAR: "my_cicd_key_secret:PRIVATE_KEY_CONTENT"
    PRIVATE_KEY_PASSPHRASE_VAR: "my_cicd_key_secret:PRIVATE_KEY_PASSPHRASE"

phases:
  install:
    commands:
      # Enable verbose output and exit immediately on error for debugging
      - cd
      - pwd
      - ls -a 

      - echo "Downloading SnowSQL CLI installer..."
      - curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.4/linux_x86_64/snowsql-1.4.3-linux_x86_64.bash

      - echo "Making installer executable..."
      - echo "Executing SnowSQL CLI installer..."
      - export SNOWSQL_DEST=./snowsql_install
      - export SNOWSQL_LOGIN_SHELL=/dev/null
      - bash snowsql-1.4.3-linux_x86_64.bash -y


      - export PATH=$PATH:./snowsql_install
      - chmod +x ./snowsql_install/snowsql
      - echo "SnowSQL CLI installed."
      - echo -e ${PATH//:/\\n}
      - snowsql -v


  build:
    commands:      
      - echo "Starting Snowflake Git Stage Refresh..."

      - echo "$PRIVATE_KEY_CONTENT_VAR" > /tmp/snowflake_private_key.p8
      - chmod 400 /tmp/snowflake_private_key.p8
      - export SNOWSQL_PRIVATE_KEY_PASSPHRASE="$PRIVATE_KEY_PASSPHRASE_VAR"

      - snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -r $SNOWFLAKE_ROLE -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE -s $SNOWFLAKE_SCHEMA --private-key-path /tmp/snowflake_private_key.p8 -q "ALTER GIT REPOSITORY $SNOWFLAKE_GIT_STAGE FETCH;"

      - echo "Snowflake Git Stage Refresh completed."

      - rm /tmp/snowflake_private_key.p8

artifacts:
  files:
    - '**/*'
  discard-paths: yes